### ISSUE TITLE
how to use self-signed cert for quic listener

### ISSUE THREAD

**Issue by aa51513** [c2FmZQ/tlsproxy#132]
when I configured acceptTOS=false

I got ```acceptTOS must be set to true in the config file```in the running log

I want to know how to configure self-signed cert for quic listener

**Comment by rthellend** [comment]
tlsproxy is designed to use Let's Encrypt. It doesn't currently have an option to use other TLS certificates. It would be rather simple to add though.

If you just want to test with in-memory only certificates, you can set the `--use-ephemeral-certificate-manager` flag. Then tlsproxy will generate self-signed certificates itself. The keys and certificates will change when tlsproxy is restarted.

**Comment by aa51513** [comment]
> tlsproxy is designed to use Let's Encrypt. It doesn't currently have an option to use other TLS certificates. It would be rather simple to add though.
> 
> If you just want to test with in-memory only certificates, you can set the `--use-ephemeral-certificate-manager` flag. Then tlsproxy will generate self-signed certificates itself. The keys and certificates will change when tlsproxy is restarted.

setting the ```--use-ephemeral-certificate-manager``` flag solved the problem I was facing
Thank you ^v^
