### ISSUE TITLE
Quic Support

### ISSUE THREAD

**Issue by hiddify-com** [c2FmZQ/tlsproxy#29]
Is it in your plan to support quic also e.g. using https://github.com/quic-go/quic-go?

**Comment by rthellend** [comment]
Thanks for bringing this up. QUIC will certainly need to be added eventually.

Proxying QUIC connections should be pretty straight forward. Proxying HTTP/3 requests is quite a bit more work.

What would be your use case for tlsproxy if it supported QUIC?

**Comment by hiddify-com** [comment]
Cool, It would be a great enhancement. 

Without using Http3, would it possible to proxy quic to a http backend or we can just do `tlspassthrough`?

**Comment by rthellend** [comment]
QUIC and HTTP/3 are now available.

See https://github.com/c2FmZQ/tlsproxy/blob/main/docs/QUIC.md
