### ISSUE TITLE
Path Support

### ISSUE THREAD

**Issue by hiddify-com** [c2FmZQ/tlsproxy#30]
Is it possible to support path for proxy?

for instance `a.com/s1` and `a.com/s2` route to different backends?

PS. Path header in h2 and h3 is `:path` header

**Comment by rthellend** [comment]
Thanks for bringing this up.

Routing based on path is certainly doable. We haven't had a need for it yet. That's why we haven't added it.

Is this something you would use? Could you describe your use case a little bit more?

**Comment by hiddify-com** [comment]
Let's describe our goal and our use case.

Our objective is to develop an easy-to-use, secure, and open-source proxy server and client that supports a wide range of protocols while safeguarding them from active probing.


Imagine our proxy server is hosted at `a.com`. Under typical circumstances, if the Great Firewall of China (GFW) makes a request to `a.com`, it could potentially conduct active probing on our proxy. To counter this, our strategy involves concealing the proxy behind a secret path, `/proxy`, on the website. As all requests are encrypted using HTTPS, the GFW is unable to detect this hidden path, rendering its active probing attempts ineffective. This approach ensures that our proxy remains secure and inaccessible to such probing attempts.


in addition, since we have several protocols, like grpc, h2, http1.1, we need to be able to sperate them by path

for example
a.com/proxy/grpc -->backend1
a.com/proxy/h2 -->backend2
a.com/proxy/h1 -->backend3

**Comment by rthellend** [comment]
I see. Thanks for the details.

Adding support for path routing isn't the main issue we'd need to solve to support your use case. We'd need to add support for proxying http/2 requests first (and perhaps http/3 as well based https://github.com/c2FmZQ/tlsproxy/issues/29). GRPC uses http/2 for transport. So, it should just work if http/2 was supported.

So far, we only have support for http/1 for http reverse proxy. Path routing can be added to http/1 relatively easily.

Adding support for http/2 is a larger project. Is this something you'd be interested in contributing to?

**Comment by hiddify-com** [comment]
It is my pleasure to contribute to this great project. I am in hard period now but in one month i can manage for that

**Comment by rthellend** [comment]
Adding support for HTTP/2 was easier than I expected. I think https://github.com/c2FmZQ/tlsproxy/pull/31 should take care of it.

**Comment by hiddify-com** [comment]
That is amazing 😍

**Comment by hiddify-com** [comment]
In exploring potential optimizations for this system, I've considered a new approach. Currently, you handle h2 requests in tlsproxy, followed by initiating another h2 request to the backend. My proposition is to streamline this process by directly routing these requests to the backend (after SSL termination). This method would eliminate the redundancy of decoding and encoding h2/http1.1 twice. We could achieve this more efficiently by simply overlaying the proxy protocol on the existing packets. Do you think whether it is possible or not?

**Comment by rthellend** [comment]
If I understand correctly, your suggestion is to parse the incoming HTTP request, decide where it should be rerouted, and the _REPLAY_ it somehow?

This is more or less what `mode: TLS` or `mode: TCP` do, without actually parsing anything other than the TLS ClientHello.

With `mode: HTTPS` and `mode: HTTP`, tlsproxy acts as a http reverse proxy. It needs to modify the requests to add the `x-forwarded-for` and `via` headers, perhaps send redirects and set cookies when user authentication is enabled, etc.

**Comment by hiddify-com** [comment]
You are right. That is exactly what i mean.

Thanks

**Comment by rthellend** [comment]
Right. So, I don't think the _REPLAY_ idea will work in the context of an http reverse proxy.

**Comment by hiddify-com** [comment]
I think if we do not alter any packets it should work. I mean similar to sni proxy that we read some packets and based on the sni we forward it to a backend, similar thing should be possible in http, read first bytes of a packet and decides the backend. but i agree that it is not the priority now.

**Comment by rthellend** [comment]
Path support is available in [v0.2.0](https://github.com/c2FmZQ/tlsproxy/releases/tag/v0.2.0)
