### ISSUE TITLE
proxy proto

### ISSUE THREAD

**Issue by hiddify-com** [c2FmZQ/tlsproxy#33]
I think i have seen somewhere that you have also [proxy-protocol](https://github.com/pires/go-proxyproto). But today when i was trying to use it i couldn't find it.
I think my assumption was wrong or do you support proxy-proto?

**Comment by rthellend** [comment]
tlsproxy doesn't currently support the PROXY protocol.

It would be a pretty simple feature to add though. It's just like `mode: TCP` or `mode: TLS` but adding a short header at the beginning.

For tlsproxy to act as a proxy-proto _client_, I would suggest either:

* adding two new modes: `mode: PROXYPROTO` and `mode: PROXYPROTOTLS`. These two modes would behave exactly like `TCP` and `TLS` except that the proxy proto header would be added, or
* adding an option `enableProxyProtocol: true` that would affect `TCP` and `TLS` modes and add the proxy proto header.

I don't think it would make much sense for tlsproxy to act as a proxy-proto _server_.

**Comment by hiddify-com** [comment]
i think the second option is better by having:
``` 
proxyProtocol: v1, v2, disable (default)
``` 
to support a wide range of clients

I think also it can be good to have it in all the modes even in the http mode similar to haproxy

I agree that server is not needed

**Comment by rthellend** [comment]
Here's a basic implementation https://github.com/c2FmZQ/tlsproxy/pull/34

**Comment by hiddify-com** [comment]
That's Great thanks

**Comment by rthellend** [comment]
This is now available in v0.3.0
